services:
  - type: web
    name: turist-checkin-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DATABASE_URL
        fromDatabase:
          name: turist-checkin-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: FRONTEND_URL
        value: https://your-vercel-app.vercel.app  # Update this after Vercel deploy
      - key: OPENAI_API_KEY
        value: your-openai-api-key  # Add your OpenAI API key here
      - key: WHATSAPP_API_KEY
        value: your-whatsapp-api-key  # Add your WhatsApp API key here
      - key: WHATSAPP_PHONE_NUMBER_ID
        value: your-whatsapp-phone-number-id  # Add your WhatsApp phone number ID here
      - key: SMTP_HOST
        value: smtp.zoho.com
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_USER
        value: contact@turistintransilvania.com
      - key: SMTP_PASSWORD
        value: your-smtp-password  # Add your SMTP password here
      - key: SMTP_FROM
        value: contact@turistintransilvania.com
