services:
  - type: web
    name: turist-checkin-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DATABASE_URL
        fromDatabase:
          name: turist-checkin-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: FRONTEND_URL
        value: https://your-vercel-app.vercel.app  # Va trebui actualizat după deploy-ul pe Vercel
